# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xzel/repos/pgx-lower

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xzel/repos/pgx-lower

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xzel/repos/pgx-lower/CMakeFiles /home/xzel/repos/pgx-lower//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xzel/repos/pgx-lower/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_verbose

# Build rule for target.
test_verbose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_verbose
.PHONY : test_verbose

# fast build rule for target.
test_verbose/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_verbose.dir/build.make CMakeFiles/test_verbose.dir/build
.PHONY : test_verbose/fast

#=============================================================================
# Target rules for targets named test_multi

# Build rule for target.
test_multi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_multi
.PHONY : test_multi

# fast build rule for target.
test_multi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_multi.dir/build.make CMakeFiles/test_multi.dir/build
.PHONY : test_multi/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named vt_gen

# Build rule for target.
vt_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vt_gen
.PHONY : vt_gen

# fast build rule for target.
vt_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vt_gen.dir/build.make CMakeFiles/vt_gen.dir/build
.PHONY : vt_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named ARMTargetParserTableGen

# Build rule for target.
ARMTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ARMTargetParserTableGen
.PHONY : ARMTargetParserTableGen

# fast build rule for target.
ARMTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ARMTargetParserTableGen.dir/build.make CMakeFiles/ARMTargetParserTableGen.dir/build
.PHONY : ARMTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named AArch64TargetParserTableGen

# Build rule for target.
AArch64TargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AArch64TargetParserTableGen
.PHONY : AArch64TargetParserTableGen

# fast build rule for target.
AArch64TargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AArch64TargetParserTableGen.dir/build.make CMakeFiles/AArch64TargetParserTableGen.dir/build
.PHONY : AArch64TargetParserTableGen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISCVTargetParserTableGen.dir/build.make CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named mlir-tablegen-targets

# Build rule for target.
mlir-tablegen-targets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlir-tablegen-targets
.PHONY : mlir-tablegen-targets

# fast build rule for target.
mlir-tablegen-targets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir-tablegen-targets.dir/build.make CMakeFiles/mlir-tablegen-targets.dir/build
.PHONY : mlir-tablegen-targets/fast

#=============================================================================
# Target rules for targets named mlir-headers

# Build rule for target.
mlir-headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlir-headers
.PHONY : mlir-headers

# fast build rule for target.
mlir-headers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir-headers.dir/build.make CMakeFiles/mlir-headers.dir/build
.PHONY : mlir-headers/fast

#=============================================================================
# Target rules for targets named mlir-generic-headers

# Build rule for target.
mlir-generic-headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlir-generic-headers
.PHONY : mlir-generic-headers

# fast build rule for target.
mlir-generic-headers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir-generic-headers.dir/build.make CMakeFiles/mlir-generic-headers.dir/build
.PHONY : mlir-generic-headers/fast

#=============================================================================
# Target rules for targets named mlir-doc

# Build rule for target.
mlir-doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlir-doc
.PHONY : mlir-doc

# fast build rule for target.
mlir-doc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir-doc.dir/build.make CMakeFiles/mlir-doc.dir/build
.PHONY : mlir-doc/fast

#=============================================================================
# Target rules for targets named build_includes

# Build rule for target.
build_includes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_includes
.PHONY : build_includes

# fast build rule for target.
build_includes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_includes.dir/build.make CMakeFiles/build_includes.dir/build
.PHONY : build_includes/fast

#=============================================================================
# Target rules for targets named mlir_unit_test

# Build rule for target.
mlir_unit_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlir_unit_test
.PHONY : mlir_unit_test

# fast build rule for target.
mlir_unit_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/build
.PHONY : mlir_unit_test/fast

#=============================================================================
# Target rules for targets named runtime-header-tool

# Build rule for target.
runtime-header-tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runtime-header-tool
.PHONY : runtime-header-tool

# fast build rule for target.
runtime-header-tool/fast:
	$(MAKE) $(MAKESILENT) -f tools/build-tools/CMakeFiles/runtime-header-tool.dir/build.make tools/build-tools/CMakeFiles/runtime-header-tool.dir/build
.PHONY : runtime-header-tool/fast

#=============================================================================
# Target rules for targets named MLIRSubOpIncGen

# Build rule for target.
MLIRSubOpIncGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRSubOpIncGen
.PHONY : MLIRSubOpIncGen

# fast build rule for target.
MLIRSubOpIncGen/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRSubOpIncGen.dir/build.make src/dialects/CMakeFiles/MLIRSubOpIncGen.dir/build
.PHONY : MLIRSubOpIncGen/fast

#=============================================================================
# Target rules for targets named MLIRSubOpInterfacesIncGen

# Build rule for target.
MLIRSubOpInterfacesIncGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRSubOpInterfacesIncGen
.PHONY : MLIRSubOpInterfacesIncGen

# fast build rule for target.
MLIRSubOpInterfacesIncGen/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRSubOpInterfacesIncGen.dir/build.make src/dialects/CMakeFiles/MLIRSubOpInterfacesIncGen.dir/build
.PHONY : MLIRSubOpInterfacesIncGen/fast

#=============================================================================
# Target rules for targets named MLIRDBIncGen

# Build rule for target.
MLIRDBIncGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRDBIncGen
.PHONY : MLIRDBIncGen

# fast build rule for target.
MLIRDBIncGen/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRDBIncGen.dir/build.make src/dialects/CMakeFiles/MLIRDBIncGen.dir/build
.PHONY : MLIRDBIncGen/fast

#=============================================================================
# Target rules for targets named MLIRTupleStreamIncGen

# Build rule for target.
MLIRTupleStreamIncGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRTupleStreamIncGen
.PHONY : MLIRTupleStreamIncGen

# fast build rule for target.
MLIRTupleStreamIncGen/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRTupleStreamIncGen.dir/build.make src/dialects/CMakeFiles/MLIRTupleStreamIncGen.dir/build
.PHONY : MLIRTupleStreamIncGen/fast

#=============================================================================
# Target rules for targets named MLIRDSAIncGen

# Build rule for target.
MLIRDSAIncGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRDSAIncGen
.PHONY : MLIRDSAIncGen

# fast build rule for target.
MLIRDSAIncGen/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRDSAIncGen.dir/build.make src/dialects/CMakeFiles/MLIRDSAIncGen.dir/build
.PHONY : MLIRDSAIncGen/fast

#=============================================================================
# Target rules for targets named MLIRUtilIncGen

# Build rule for target.
MLIRUtilIncGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRUtilIncGen
.PHONY : MLIRUtilIncGen

# fast build rule for target.
MLIRUtilIncGen/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRUtilIncGen.dir/build.make src/dialects/CMakeFiles/MLIRUtilIncGen.dir/build
.PHONY : MLIRUtilIncGen/fast

#=============================================================================
# Target rules for targets named MLIRRelAlgIncGen

# Build rule for target.
MLIRRelAlgIncGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRRelAlgIncGen
.PHONY : MLIRRelAlgIncGen

# fast build rule for target.
MLIRRelAlgIncGen/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRRelAlgIncGen.dir/build.make src/dialects/CMakeFiles/MLIRRelAlgIncGen.dir/build
.PHONY : MLIRRelAlgIncGen/fast

#=============================================================================
# Target rules for targets named MLIRSubOpDialect

# Build rule for target.
MLIRSubOpDialect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRSubOpDialect
.PHONY : MLIRSubOpDialect

# fast build rule for target.
MLIRSubOpDialect/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRSubOpDialect.dir/build.make src/dialects/CMakeFiles/MLIRSubOpDialect.dir/build
.PHONY : MLIRSubOpDialect/fast

#=============================================================================
# Target rules for targets named MLIRDBDialect

# Build rule for target.
MLIRDBDialect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRDBDialect
.PHONY : MLIRDBDialect

# fast build rule for target.
MLIRDBDialect/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRDBDialect.dir/build.make src/dialects/CMakeFiles/MLIRDBDialect.dir/build
.PHONY : MLIRDBDialect/fast

#=============================================================================
# Target rules for targets named MLIRTupleStreamDialect

# Build rule for target.
MLIRTupleStreamDialect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRTupleStreamDialect
.PHONY : MLIRTupleStreamDialect

# fast build rule for target.
MLIRTupleStreamDialect/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRTupleStreamDialect.dir/build.make src/dialects/CMakeFiles/MLIRTupleStreamDialect.dir/build
.PHONY : MLIRTupleStreamDialect/fast

#=============================================================================
# Target rules for targets named MLIRDSADialect

# Build rule for target.
MLIRDSADialect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRDSADialect
.PHONY : MLIRDSADialect

# fast build rule for target.
MLIRDSADialect/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRDSADialect.dir/build.make src/dialects/CMakeFiles/MLIRDSADialect.dir/build
.PHONY : MLIRDSADialect/fast

#=============================================================================
# Target rules for targets named MLIRRelAlgDialect

# Build rule for target.
MLIRRelAlgDialect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRRelAlgDialect
.PHONY : MLIRRelAlgDialect

# fast build rule for target.
MLIRRelAlgDialect/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRRelAlgDialect.dir/build.make src/dialects/CMakeFiles/MLIRRelAlgDialect.dir/build
.PHONY : MLIRRelAlgDialect/fast

#=============================================================================
# Target rules for targets named MLIRUtilDialect

# Build rule for target.
MLIRUtilDialect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLIRUtilDialect
.PHONY : MLIRUtilDialect

# fast build rule for target.
MLIRUtilDialect/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/MLIRUtilDialect.dir/build.make src/dialects/CMakeFiles/MLIRUtilDialect.dir/build
.PHONY : MLIRUtilDialect/fast

#=============================================================================
# Target rules for targets named PgxLowerRuntime

# Build rule for target.
PgxLowerRuntime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PgxLowerRuntime
.PHONY : PgxLowerRuntime

# fast build rule for target.
PgxLowerRuntime/fast:
	$(MAKE) $(MAKESILENT) -f src/dialects/CMakeFiles/PgxLowerRuntime.dir/build.make src/dialects/CMakeFiles/PgxLowerRuntime.dir/build
.PHONY : PgxLowerRuntime/fast

#=============================================================================
# Target rules for targets named pgx_lower

# Build rule for target.
pgx_lower: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pgx_lower
.PHONY : pgx_lower

# fast build rule for target.
pgx_lower/fast:
	$(MAKE) $(MAKESILENT) -f extension/CMakeFiles/pgx_lower.dir/build.make extension/CMakeFiles/pgx_lower.dir/build
.PHONY : pgx_lower/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/core/error_handling.o: src/core/error_handling.cpp.o
.PHONY : src/core/error_handling.o

# target to build an object file
src/core/error_handling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/error_handling.cpp.o
.PHONY : src/core/error_handling.cpp.o

src/core/error_handling.i: src/core/error_handling.cpp.i
.PHONY : src/core/error_handling.i

# target to preprocess a source file
src/core/error_handling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/error_handling.cpp.i
.PHONY : src/core/error_handling.cpp.i

src/core/error_handling.s: src/core/error_handling.cpp.s
.PHONY : src/core/error_handling.s

# target to generate assembly for a file
src/core/error_handling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/error_handling.cpp.s
.PHONY : src/core/error_handling.cpp.s

src/core/logging.o: src/core/logging.cpp.o
.PHONY : src/core/logging.o

# target to build an object file
src/core/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/logging.cpp.o
.PHONY : src/core/logging.cpp.o

src/core/logging.i: src/core/logging.cpp.i
.PHONY : src/core/logging.i

# target to preprocess a source file
src/core/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/logging.cpp.i
.PHONY : src/core/logging.cpp.i

src/core/logging.s: src/core/logging.cpp.s
.PHONY : src/core/logging.s

# target to generate assembly for a file
src/core/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/logging.cpp.s
.PHONY : src/core/logging.cpp.s

src/core/mlir_runner.o: src/core/mlir_runner.cpp.o
.PHONY : src/core/mlir_runner.o

# target to build an object file
src/core/mlir_runner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/mlir_runner.cpp.o
.PHONY : src/core/mlir_runner.cpp.o

src/core/mlir_runner.i: src/core/mlir_runner.cpp.i
.PHONY : src/core/mlir_runner.i

# target to preprocess a source file
src/core/mlir_runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/mlir_runner.cpp.i
.PHONY : src/core/mlir_runner.cpp.i

src/core/mlir_runner.s: src/core/mlir_runner.cpp.s
.PHONY : src/core/mlir_runner.s

# target to generate assembly for a file
src/core/mlir_runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/mlir_runner.cpp.s
.PHONY : src/core/mlir_runner.cpp.s

src/core/query_analyzer.o: src/core/query_analyzer.cpp.o
.PHONY : src/core/query_analyzer.o

# target to build an object file
src/core/query_analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/query_analyzer.cpp.o
.PHONY : src/core/query_analyzer.cpp.o

src/core/query_analyzer.i: src/core/query_analyzer.cpp.i
.PHONY : src/core/query_analyzer.i

# target to preprocess a source file
src/core/query_analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/query_analyzer.cpp.i
.PHONY : src/core/query_analyzer.cpp.i

src/core/query_analyzer.s: src/core/query_analyzer.cpp.s
.PHONY : src/core/query_analyzer.s

# target to generate assembly for a file
src/core/query_analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/core/query_analyzer.cpp.s
.PHONY : src/core/query_analyzer.cpp.s

src/logging/console_logger.o: src/logging/console_logger.cpp.o
.PHONY : src/logging/console_logger.o

# target to build an object file
src/logging/console_logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/logging/console_logger.cpp.o
.PHONY : src/logging/console_logger.cpp.o

src/logging/console_logger.i: src/logging/console_logger.cpp.i
.PHONY : src/logging/console_logger.i

# target to preprocess a source file
src/logging/console_logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/logging/console_logger.cpp.i
.PHONY : src/logging/console_logger.cpp.i

src/logging/console_logger.s: src/logging/console_logger.cpp.s
.PHONY : src/logging/console_logger.s

# target to generate assembly for a file
src/logging/console_logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/src/logging/console_logger.cpp.s
.PHONY : src/logging/console_logger.cpp.s

tests/unit/core/error_handling_test.o: tests/unit/core/error_handling_test.cpp.o
.PHONY : tests/unit/core/error_handling_test.o

# target to build an object file
tests/unit/core/error_handling_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/error_handling_test.cpp.o
.PHONY : tests/unit/core/error_handling_test.cpp.o

tests/unit/core/error_handling_test.i: tests/unit/core/error_handling_test.cpp.i
.PHONY : tests/unit/core/error_handling_test.i

# target to preprocess a source file
tests/unit/core/error_handling_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/error_handling_test.cpp.i
.PHONY : tests/unit/core/error_handling_test.cpp.i

tests/unit/core/error_handling_test.s: tests/unit/core/error_handling_test.cpp.s
.PHONY : tests/unit/core/error_handling_test.s

# target to generate assembly for a file
tests/unit/core/error_handling_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/error_handling_test.cpp.s
.PHONY : tests/unit/core/error_handling_test.cpp.s

tests/unit/core/mlir_logger_test.o: tests/unit/core/mlir_logger_test.cpp.o
.PHONY : tests/unit/core/mlir_logger_test.o

# target to build an object file
tests/unit/core/mlir_logger_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/mlir_logger_test.cpp.o
.PHONY : tests/unit/core/mlir_logger_test.cpp.o

tests/unit/core/mlir_logger_test.i: tests/unit/core/mlir_logger_test.cpp.i
.PHONY : tests/unit/core/mlir_logger_test.i

# target to preprocess a source file
tests/unit/core/mlir_logger_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/mlir_logger_test.cpp.i
.PHONY : tests/unit/core/mlir_logger_test.cpp.i

tests/unit/core/mlir_logger_test.s: tests/unit/core/mlir_logger_test.cpp.s
.PHONY : tests/unit/core/mlir_logger_test.s

# target to generate assembly for a file
tests/unit/core/mlir_logger_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/mlir_logger_test.cpp.s
.PHONY : tests/unit/core/mlir_logger_test.cpp.s

tests/unit/core/mlir_runner_test.o: tests/unit/core/mlir_runner_test.cpp.o
.PHONY : tests/unit/core/mlir_runner_test.o

# target to build an object file
tests/unit/core/mlir_runner_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/mlir_runner_test.cpp.o
.PHONY : tests/unit/core/mlir_runner_test.cpp.o

tests/unit/core/mlir_runner_test.i: tests/unit/core/mlir_runner_test.cpp.i
.PHONY : tests/unit/core/mlir_runner_test.i

# target to preprocess a source file
tests/unit/core/mlir_runner_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/mlir_runner_test.cpp.i
.PHONY : tests/unit/core/mlir_runner_test.cpp.i

tests/unit/core/mlir_runner_test.s: tests/unit/core/mlir_runner_test.cpp.s
.PHONY : tests/unit/core/mlir_runner_test.s

# target to generate assembly for a file
tests/unit/core/mlir_runner_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/mlir_runner_test.cpp.s
.PHONY : tests/unit/core/mlir_runner_test.cpp.s

tests/unit/core/query_analyzer_test.o: tests/unit/core/query_analyzer_test.cpp.o
.PHONY : tests/unit/core/query_analyzer_test.o

# target to build an object file
tests/unit/core/query_analyzer_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/query_analyzer_test.cpp.o
.PHONY : tests/unit/core/query_analyzer_test.cpp.o

tests/unit/core/query_analyzer_test.i: tests/unit/core/query_analyzer_test.cpp.i
.PHONY : tests/unit/core/query_analyzer_test.i

# target to preprocess a source file
tests/unit/core/query_analyzer_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/query_analyzer_test.cpp.i
.PHONY : tests/unit/core/query_analyzer_test.cpp.i

tests/unit/core/query_analyzer_test.s: tests/unit/core/query_analyzer_test.cpp.s
.PHONY : tests/unit/core/query_analyzer_test.s

# target to generate assembly for a file
tests/unit/core/query_analyzer_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/core/query_analyzer_test.cpp.s
.PHONY : tests/unit/core/query_analyzer_test.cpp.s

tests/unit/runtime/tuple_access_test.o: tests/unit/runtime/tuple_access_test.cpp.o
.PHONY : tests/unit/runtime/tuple_access_test.o

# target to build an object file
tests/unit/runtime/tuple_access_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/runtime/tuple_access_test.cpp.o
.PHONY : tests/unit/runtime/tuple_access_test.cpp.o

tests/unit/runtime/tuple_access_test.i: tests/unit/runtime/tuple_access_test.cpp.i
.PHONY : tests/unit/runtime/tuple_access_test.i

# target to preprocess a source file
tests/unit/runtime/tuple_access_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/runtime/tuple_access_test.cpp.i
.PHONY : tests/unit/runtime/tuple_access_test.cpp.i

tests/unit/runtime/tuple_access_test.s: tests/unit/runtime/tuple_access_test.cpp.s
.PHONY : tests/unit/runtime/tuple_access_test.s

# target to generate assembly for a file
tests/unit/runtime/tuple_access_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/runtime/tuple_access_test.cpp.s
.PHONY : tests/unit/runtime/tuple_access_test.cpp.s

tests/unit/test_helpers.o: tests/unit/test_helpers.cpp.o
.PHONY : tests/unit/test_helpers.o

# target to build an object file
tests/unit/test_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/test_helpers.cpp.o
.PHONY : tests/unit/test_helpers.cpp.o

tests/unit/test_helpers.i: tests/unit/test_helpers.cpp.i
.PHONY : tests/unit/test_helpers.i

# target to preprocess a source file
tests/unit/test_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/test_helpers.cpp.i
.PHONY : tests/unit/test_helpers.cpp.i

tests/unit/test_helpers.s: tests/unit/test_helpers.cpp.s
.PHONY : tests/unit/test_helpers.s

# target to generate assembly for a file
tests/unit/test_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/test_helpers.cpp.s
.PHONY : tests/unit/test_helpers.cpp.s

tests/unit/test_main.o: tests/unit/test_main.cpp.o
.PHONY : tests/unit/test_main.o

# target to build an object file
tests/unit/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/test_main.cpp.o
.PHONY : tests/unit/test_main.cpp.o

tests/unit/test_main.i: tests/unit/test_main.cpp.i
.PHONY : tests/unit/test_main.i

# target to preprocess a source file
tests/unit/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/test_main.cpp.i
.PHONY : tests/unit/test_main.cpp.i

tests/unit/test_main.s: tests/unit/test_main.cpp.s
.PHONY : tests/unit/test_main.s

# target to generate assembly for a file
tests/unit/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/test_main.cpp.s
.PHONY : tests/unit/test_main.cpp.s

tests/unit/test_subop_simple.o: tests/unit/test_subop_simple.cpp.o
.PHONY : tests/unit/test_subop_simple.o

# target to build an object file
tests/unit/test_subop_simple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/test_subop_simple.cpp.o
.PHONY : tests/unit/test_subop_simple.cpp.o

tests/unit/test_subop_simple.i: tests/unit/test_subop_simple.cpp.i
.PHONY : tests/unit/test_subop_simple.i

# target to preprocess a source file
tests/unit/test_subop_simple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/test_subop_simple.cpp.i
.PHONY : tests/unit/test_subop_simple.cpp.i

tests/unit/test_subop_simple.s: tests/unit/test_subop_simple.cpp.s
.PHONY : tests/unit/test_subop_simple.s

# target to generate assembly for a file
tests/unit/test_subop_simple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlir_unit_test.dir/build.make CMakeFiles/mlir_unit_test.dir/tests/unit/test_subop_simple.cpp.s
.PHONY : tests/unit/test_subop_simple.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... AArch64TargetParserTableGen"
	@echo "... ARMTargetParserTableGen"
	@echo "... MLIRDBIncGen"
	@echo "... MLIRDSAIncGen"
	@echo "... MLIRRelAlgIncGen"
	@echo "... MLIRSubOpIncGen"
	@echo "... MLIRSubOpInterfacesIncGen"
	@echo "... MLIRTupleStreamIncGen"
	@echo "... MLIRUtilIncGen"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... build_includes"
	@echo "... intrinsics_gen"
	@echo "... mlir-doc"
	@echo "... mlir-generic-headers"
	@echo "... mlir-headers"
	@echo "... mlir-tablegen-targets"
	@echo "... omp_gen"
	@echo "... test_multi"
	@echo "... test_verbose"
	@echo "... vt_gen"
	@echo "... MLIRDBDialect"
	@echo "... MLIRDSADialect"
	@echo "... MLIRRelAlgDialect"
	@echo "... MLIRSubOpDialect"
	@echo "... MLIRTupleStreamDialect"
	@echo "... MLIRUtilDialect"
	@echo "... PgxLowerRuntime"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... mlir_unit_test"
	@echo "... pgx_lower"
	@echo "... runtime-header-tool"
	@echo "... src/core/error_handling.o"
	@echo "... src/core/error_handling.i"
	@echo "... src/core/error_handling.s"
	@echo "... src/core/logging.o"
	@echo "... src/core/logging.i"
	@echo "... src/core/logging.s"
	@echo "... src/core/mlir_runner.o"
	@echo "... src/core/mlir_runner.i"
	@echo "... src/core/mlir_runner.s"
	@echo "... src/core/query_analyzer.o"
	@echo "... src/core/query_analyzer.i"
	@echo "... src/core/query_analyzer.s"
	@echo "... src/logging/console_logger.o"
	@echo "... src/logging/console_logger.i"
	@echo "... src/logging/console_logger.s"
	@echo "... tests/unit/core/error_handling_test.o"
	@echo "... tests/unit/core/error_handling_test.i"
	@echo "... tests/unit/core/error_handling_test.s"
	@echo "... tests/unit/core/mlir_logger_test.o"
	@echo "... tests/unit/core/mlir_logger_test.i"
	@echo "... tests/unit/core/mlir_logger_test.s"
	@echo "... tests/unit/core/mlir_runner_test.o"
	@echo "... tests/unit/core/mlir_runner_test.i"
	@echo "... tests/unit/core/mlir_runner_test.s"
	@echo "... tests/unit/core/query_analyzer_test.o"
	@echo "... tests/unit/core/query_analyzer_test.i"
	@echo "... tests/unit/core/query_analyzer_test.s"
	@echo "... tests/unit/runtime/tuple_access_test.o"
	@echo "... tests/unit/runtime/tuple_access_test.i"
	@echo "... tests/unit/runtime/tuple_access_test.s"
	@echo "... tests/unit/test_helpers.o"
	@echo "... tests/unit/test_helpers.i"
	@echo "... tests/unit/test_helpers.s"
	@echo "... tests/unit/test_main.o"
	@echo "... tests/unit/test_main.i"
	@echo "... tests/unit/test_main.s"
	@echo "... tests/unit/test_subop_simple.o"
	@echo "... tests/unit/test_subop_simple.i"
	@echo "... tests/unit/test_subop_simple.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

