#include "compiler/Dialect/RelAlg/RelAlgDialect.h"
#include "compiler/Dialect/RelAlg/RelAlgOps.h"
#include "compiler/Dialect/RelAlg/Catalog.h"
#include "compiler/Dialect/DB/DBDialect.h"
#include "compiler/Dialect/TupleStream/TupleStreamDialect.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"

// Include MetaDataHash.h right before we need it
#include "catalog/MetaDataHash.h"

using namespace mlir;
using namespace pgx_lower::compiler::dialect::relalg;

void RelAlgDialect::initialize() {
    // Add operations from TableGen
    addOperations<
#define GET_OP_LIST
#include "RelAlgOps.cpp.inc"
    >();
    
    // Add attributes from TableGen
    addAttributes<
#define GET_ATTRDEF_LIST
#include "RelAlgAttrs.cpp.inc"
    >();
    
    // Load dependent dialects
    getContext()->loadDialect<pgx_lower::compiler::dialect::db::DBDialect>();
    getContext()->loadDialect<mlir::arith::ArithDialect>();
    getContext()->loadDialect<pgx_lower::compiler::dialect::tuples::TupleStreamDialect>();
}

// parseAttribute and printAttribute are generated by TableGen in RelAlgAttrs.cpp.inc

// Include generated dialect implementation
#include "RelAlgDialect.cpp.inc"

// Include generated enum definitions
#include "RelAlgEnums.cpp.inc"

// Include generated attribute definitions
#define GET_ATTRDEF_CLASSES
#include "RelAlgAttrs.cpp.inc"