import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "vitest";
import { collectPgTestFunctions, generateUnitSql, runUnitSqlCommand, writeUnitSqlFiles } from "../src/unit-sql.js";

describe("unit SQL generation", () => {
  test("collects PGX_TEST_FN declarations", () => {
    expect(collectPgTestFunctions("PGX_TEST_FN(alpha)\nPGX_TEST_FN( beta )\n")).toEqual(["alpha", "beta"]);
  });

  test("renders the expected SQL wrapper", () => {
    const sql = generateUnitSql("numeric_tests.cpp", ["numeric_add_basic"]);

    expect(sql).toContain("AUTOGENERATED by pgx-cli");
    expect(sql).toContain("CREATE OR REPLACE FUNCTION test.numeric_add_basic() RETURNS VOID");
    expect(sql).toContain("AS '$libdir/pgx_lower', 'ts_test_numeric_add_basic'");
    expect(sql).toContain("PERFORM test.numeric_add_basic();");
  });

  test("writes one sql file per *_tests.cpp source with functions", () => {
    const root = mkdtempSync(join(tmpdir(), "pgx-unit-sql-"));
    const srcDir = join(root, "src/pgx-lower/test");
    const outDir = join(root, "tests/unit-tests/sql");
    mkdirSync(srcDir, { recursive: true });
    mkdirSync(outDir, { recursive: true });
    writeFileSync(join(srcDir, "numeric_tests.cpp"), "PGX_TEST_FN(numeric_add_basic)\n", { flag: "w" });

    const written = writeUnitSqlFiles(root);

    expect(written).toEqual(["tests/unit-tests/sql/numeric.sql (1 tests)"]);
    expect(readFileSync(join(outDir, "numeric.sql"), "utf8")).toContain("numeric_add_basic");
  });

  test("replaces existing generated sql files that are not writable", () => {
    const root = mkdtempSync(join(tmpdir(), "pgx-unit-sql-"));
    const srcDir = join(root, "src/pgx-lower/test");
    const outDir = join(root, "tests/unit-tests/sql");
    const out = join(outDir, "numeric.sql");
    mkdirSync(srcDir, { recursive: true });
    mkdirSync(outDir, { recursive: true });
    writeFileSync(join(srcDir, "numeric_tests.cpp"), "PGX_TEST_FN(numeric_add_basic)\n", { flag: "w" });
    writeFileSync(out, "stale\n", { mode: 0o444 });
    chmodSync(out, 0o444);

    const written = writeUnitSqlFiles(root);

    expect(written).toEqual(["tests/unit-tests/sql/numeric.sql (1 tests)"]);
    expect(readFileSync(out, "utf8")).toContain("numeric_add_basic");
  });

  test("removes stale autogenerated sql files without deleting manual sql", () => {
    const root = mkdtempSync(join(tmpdir(), "pgx-unit-sql-"));
    const srcDir = join(root, "src/pgx-lower/test");
    const outDir = join(root, "tests/unit-tests/sql");
    mkdirSync(srcDir, { recursive: true });
    mkdirSync(outDir, { recursive: true });
    writeFileSync(join(srcDir, "numeric_tests.cpp"), "PGX_TEST_FN(numeric_add_basic)\n", { flag: "w" });
    writeFileSync(join(outDir, "old.sql"), "-- AUTOGENERATED by pgx-cli - do not edit by hand.\n");
    writeFileSync(join(outDir, "manual.sql"), "SELECT 1;\n");

    writeUnitSqlFiles(root);

    expect(existsSync(join(outDir, "old.sql"))).toBe(false);
    expect(existsSync(join(outDir, "manual.sql"))).toBe(true);
    expect(existsSync(join(outDir, "numeric.sql"))).toBe(true);
  });

  test("removes stale autogenerated sql when a source has no PGX tests", () => {
    const root = mkdtempSync(join(tmpdir(), "pgx-unit-sql-"));
    const srcDir = join(root, "src/pgx-lower/test");
    const outDir = join(root, "tests/unit-tests/sql");
    mkdirSync(srcDir, { recursive: true });
    mkdirSync(outDir, { recursive: true });
    writeFileSync(join(srcDir, "empty_tests.cpp"), "int helper_only;\n", { flag: "w" });
    writeFileSync(join(outDir, "empty.sql"), "-- AUTOGENERATED by pgx-cli - do not edit by hand.\n");

    writeUnitSqlFiles(root);

    expect(existsSync(join(outDir, "empty.sql"))).toBe(false);
  });

  test("runs the unit-sql command for an explicit root", () => {
    const root = mkdtempSync(join(tmpdir(), "pgx-unit-sql-"));
    const srcDir = join(root, "src/pgx-lower/test");
    mkdirSync(srcDir, { recursive: true });
    writeFileSync(join(srcDir, "numeric_tests.cpp"), "PGX_TEST_FN(numeric_add_basic)\n", { flag: "w" });
    const io = { stdout: "", stderr: "" };

    const exitCode = runUnitSqlCommand(["--root", root], io);

    expect(exitCode).toBe(0);
    expect(io.stdout).toContain("tests/unit-tests/sql/numeric.sql (1 tests)");
  });
});
