//===----------------------------------------------------------------------===//
// RelAlg Types
//===----------------------------------------------------------------------===//

#ifndef RELALG_TYPES
#define RELALG_TYPES

include "mlir/IR/AttrTypeBase.td"
include "compiler/Dialect/RelAlg/RelAlgBase.td"

// The RelAlg dialect reuses TupleStreamType from the tuplestream dialect
// No custom types defined for RelAlg

#endif // RELALG_TYPES