#!/usr/bin/env python3
"""Generate tests/regress-unit/sql/*.sql from src/pgx-lower/test/*_tests.cpp.

Each *_tests.cpp file contains PG_FUNCTION_INFO_V1(ts_test_<name>) declarations.
For numeric_tests.cpp -> numeric.sql with one CREATE FUNCTION per ts_test_*
symbol plus a DO block that PERFORMs each.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEST_SRC_DIR = ROOT / "src" / "pgx-lower" / "test"
SQL_OUT_DIR = ROOT / "tests" / "regress-unit" / "sql"

PG_FN_RE = re.compile(r"PG_FUNCTION_INFO_V1\(\s*(ts_test_\w+)\s*\)")

HEADER = "-- AUTOGENERATED by scripts/gen_unit_test_sql.py — do not edit by hand.\n-- Source: src/pgx-lower/test/{src}\n\n"


def collect_tests(cpp_path: Path) -> list[str]:
    text = cpp_path.read_text()
    return [m.group(1) for m in PG_FN_RE.finditer(text)]


def emit_sql(group: str, src_basename: str, tests: list[str]) -> str:
    lines = [HEADER.format(src=src_basename)]
    lines.append("\\set ON_ERROR_STOP on\n")
    lines.append("\nCREATE SCHEMA IF NOT EXISTS test;\n")
    for sym in tests:
        sql_name = sym.removeprefix("ts_test_")
        lines.append(
            f"\nCREATE OR REPLACE FUNCTION test.{sql_name}() RETURNS VOID\n"
            f"    AS '$libdir/pgx_lower', '{sym}' LANGUAGE C VOLATILE;"
        )
    lines.append("\n\nDO $$ BEGIN")
    for sym in tests:
        sql_name = sym.removeprefix("ts_test_")
        lines.append(f"\n    PERFORM test.{sql_name}();")
    lines.append("\nEND $$;\n")
    lines.append("\nDROP SCHEMA test CASCADE;\n")
    return "".join(lines)


def main() -> int:
    SQL_OUT_DIR.mkdir(parents=True, exist_ok=True)
    sources = sorted(TEST_SRC_DIR.glob("*_tests.cpp"))
    if not sources:
        print(f"no *_tests.cpp under {TEST_SRC_DIR}", file=sys.stderr)
        return 1
    written = []
    for cpp in sources:
        tests = collect_tests(cpp)
        if not tests:
            continue
        group = cpp.stem.removesuffix("_tests")
        out = SQL_OUT_DIR / f"{group}.sql"
        out.write_text(emit_sql(group, cpp.name, tests))
        written.append(f"{out.relative_to(ROOT)} ({len(tests)} tests)")
    for w in written:
        print(w)
    return 0


if __name__ == "__main__":
    sys.exit(main())
