import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

export type CommandPolicyDecision =
  | { decision: "allow"; reason: string }
  | { decision: "forbidden"; reason: string; replacement: string };

const blockedCommands = [
  ["ssh", "pgx-cli run thor -- ..."],
  ["docker", "pgx-cli run docker -- ..."],
  ["psql", "pgx-cli run psql ..."],
  ["pg_regress", "pgx-cli dev test ..."],
  ["ctest", "pgx-cli dev test ..."],
  ["cmake", "pgx-cli dev build ..."],
  ["ninja", "pgx-cli dev build ..."],
  ["tsp", "pgx-cli queue ..."],
  ["mutagen", "pgx-cli sync ..."],
  ["just", "pgx-cli ..."]
] as const;

const localInspectionCommands = new Set(["rg", "sed", "find", "ls", "pwd", "nl", "wc"]);
const shellWrapperCommands = new Set(["bash", "sh", "zsh"]);

const broadBypassRules = [
  {
    pattern: ["bash", "-lc"],
    replacement: "pgx-cli typed commands or non-opaque local inspection"
  },
  {
    pattern: ["bash", "-c"],
    replacement: "pgx-cli typed commands or non-opaque local inspection"
  },
  {
    pattern: ["sh", "-c"],
    replacement: "pgx-cli typed commands or non-opaque local inspection"
  },
  {
    pattern: ["zsh", "-lc"],
    replacement: "pgx-cli typed commands or non-opaque local inspection"
  },
  {
    pattern: ["zsh", "-c"],
    replacement: "pgx-cli typed commands or non-opaque local inspection"
  },
  {
    pattern: ["cat"],
    replacement: "pgx-cli logs ... / pgx-cli ir inspect ... / sed -n for small source reads"
  },
  {
    pattern: ["tail"],
    replacement: "pgx-cli logs ... / pgx-cli ir inspect ..."
  },
  {
    pattern: ["gh", "pr", "comment", "1", "--body", "`pgx-cli dev gate review`"],
    replacement: "gh pr comment --body-file"
  }
] as const;

const retiredWorkflowScripts = [
  "benchmark/tpch/aggregate.py",
  "benchmark/tpch/fxt_to_flamegraph.py",
  "benchmark/tpch/metrics_collector.py",
  "benchmark/tpch/run.py"
];

const agentEfficiencyRules = [
  "## Agent Efficiency Rules",
  "",
  "- Use `pgx-cli` for high-risk commands: thor, Docker, PostgreSQL, CTest, CMake,",
  "  Ninja, task-spooler, Mutagen, benchmarks, and migrated helper scripts.",
  "- Do not raw-cat large logs or IR dumps. Use `pgx-cli logs ...` or",
  "  `pgx-cli ir inspect ...`.",
  "- After a full gate failure, run the focused reproducer before rerunning the",
  "  full gate.",
  "- Before claiming PR-ready, run the evidence/readiness checks required by the",
  "  active spec.",
  "- Edit local files and run compute on thor. Do not edit source directly in the",
  "  thor checkout.",
  "- Treat generated and ignored artifacts as execution state that must be fresh."
] as const;

export function classifyAgentCommand(
  argv: string[],
  options: { root?: string; workflowScripts?: string[] } = {}
): CommandPolicyDecision {
  const command = argv[0] ?? "";
  const workflowScripts = options.workflowScripts ?? (options.root ? discoverWorkflowScripts(options.root) : []);
  const normalizedScripts = new Set(workflowScripts.flatMap((script) => [script, `./${script}`]));
  if (normalizedScripts.has(command)) {
    return forbid(command, "pgx-cli <typed workflow command>");
  }

  if (containsShellBacktickBody(argv)) {
    return forbid("gh pr comment --body", "gh pr comment --body-file");
  }
  const shellBody = shellWrapperBody(argv);
  if (shellBody !== undefined) {
    const shellDecision = classifyShellBody(shellBody);
    if (shellDecision) return shellDecision;
  }
  const dangerousReadReplacement = largeReadReplacement(argv);
  if (dangerousReadReplacement) {
    return forbid(command, dangerousReadReplacement);
  }
  const blocked = blockedCommands.find(([binary]) => binary === command);
  if (blocked) {
    return forbid(command, blocked[1]);
  }
  if (command === "pgx-cli") {
    return { decision: "allow", reason: "pgx-cli gateway command" };
  }
  if (localInspectionCommands.has(command)) {
    return { decision: "allow", reason: "local read-only inspection command" };
  }
  if (command === "git" && ["status", "diff", "show"].includes(argv[1] ?? "")) {
    return { decision: "allow", reason: "local git inspection command" };
  }
  return { decision: "allow", reason: "not covered by pgx-lower agent workflow policy" };
}

export function discoverWorkflowScripts(root: string): string[] {
  return [...new Set([
    ...filesIn(join(root, "scripts"), "scripts", (name) => name.endsWith(".sh")),
    ...filesIn(join(root, "tools", "scripts"), "tools/scripts", (name) => name.endsWith(".sh") || name.endsWith(".py")),
    ...filesIn(join(root, "benchmark"), "benchmark", (name) => name.endsWith(".py")),
    ...retiredWorkflowScripts
  ])].sort();
}

export function renderDefaultRules(options: { root?: string; workflowScripts?: string[] } = {}): string {
  const scripts = options.workflowScripts ?? (options.root ? discoverWorkflowScripts(options.root) : []);
  const chunks: string[] = [[
    "# Generated by `pgx-cli codex-policy rules`.",
    "# match: ssh comfy true",
    "# match: docker ps",
    "# match: psql -c 'SELECT 1'",
    "# Opaque shell wrappers and raw cat/tail are blocked below because",
    "# project rules cannot match arbitrary shell-body or path substrings.",
    "# Use typed pgx-cli commands, direct local inspection commands, or",
    "# `pgx-cli codex-policy check -- <cmd...>` for detailed classifier output.",
    "",
    ...agentEfficiencyRules.map((line) => line ? `# ${line}` : "#")
  ].join("\n")];
  for (const [command, replacement] of blockedCommands) {
    chunks.push(prefixRule([command], replacement));
  }
  for (const rule of broadBypassRules) {
    chunks.push(prefixRule([...rule.pattern], rule.replacement));
  }
  for (const script of scripts) {
    chunks.push(prefixRule([script], "pgx-cli <typed workflow command>"));
    chunks.push(prefixRule([`./${script}`], "pgx-cli <typed workflow command>"));
  }
  return `${chunks.join("\n\n")}\n`;
}

export function runCodexPolicyCommand(args: string[], output: { stdout: string; stderr: string }): number {
  const [command, ...rest] = args;
  if (command === "rules") {
    output.stdout += renderDefaultRules({ root: process.cwd() });
    return 0;
  }
  if (command === "check") {
    const separator = rest.indexOf("--");
    const argv = separator === -1 ? rest : rest.slice(separator + 1);
    const decision = classifyAgentCommand(argv, { root: process.cwd() });
    output.stdout += `${JSON.stringify(decision, null, 2)}\n`;
    return decision.decision === "forbidden" ? 1 : 0;
  }
  output.stderr += "Usage: codex-policy <check -- <cmd...>|rules>\n";
  return 1;
}

function forbid(command: string, replacement: string): CommandPolicyDecision {
  return {
    decision: "forbidden",
    reason: `Use ${replacement} so Mutagen, transcripts, and output limits are enforced instead of raw ${command}.`,
    replacement
  };
}

function classifyShellBody(script: string): CommandPolicyDecision | undefined {
  const blocked = blockedCommands.find(([binary]) => startsOrChainsInto(script, binary));
  if (blocked) {
    return forbid(blocked[0], blocked[1]);
  }
  if (containsDangerousLogRead(script)) {
    return forbid("large log/IR read", largeReadReplacement(script) ?? "pgx-cli logs ...");
  }
  if (containsShellBacktickBody(splitShellWords(script)) || containsGhBacktickBody(script)) {
    return forbid("gh pr comment --body", "gh pr comment --body-file");
  }
  return undefined;
}

function containsDangerousLogRead(script: string): boolean {
  return largeReadReplacement(script) !== undefined;
}

function containsShellBacktickBody(argv: string[]): boolean {
  if (argv[0] !== "gh" || argv[1] !== "pr" || argv[2] !== "comment") return false;
  for (let index = 3; index < argv.length; index += 1) {
    const arg = argv[index] ?? "";
    if (arg === "--body") return (argv[index + 1] ?? "").includes("`");
    if (arg.startsWith("--body=")) return arg.slice("--body=".length).includes("`");
  }
  return false;
}

function shellWrapperBody(argv: string[]): string | undefined {
  if (!shellWrapperCommands.has(argv[0] ?? "")) return undefined;
  for (let index = 1; index < argv.length - 1; index += 1) {
    const arg = argv[index] ?? "";
    if (arg === "-c" || (arg.startsWith("-") && arg.endsWith("c"))) {
      return argv[index + 1];
    }
  }
  return undefined;
}

function startsOrChainsInto(script: string, command: string): boolean {
  return new RegExp(`(?:^|[;&|\\n])\\s*${escapeRegExp(command)}\\b`).test(script);
}

function largeReadReplacement(argvOrScript: string[] | string): string | undefined {
  if (Array.isArray(argvOrScript)) {
    if (!["cat", "tail", "find"].includes(argvOrScript[0] ?? "")) return undefined;
    return replacementForPath(argvOrScript.find((arg) => isLargeLogOrIrPath(arg)));
  }
  const commandPrefix = "(?:^|[;&|\\n])\\s*(?:cat|tail|find)\\b[^;&|\\n]*";
  if (new RegExp(`${commandPrefix}${escapeRegExp("/tmp/pgx_errors.log")}\\b`).test(argvOrScript)) {
    return "pgx-cli logs errors";
  }
  if (new RegExp(`${commandPrefix}${escapeRegExp("/tmp/pgx_ir")}\\b`).test(argvOrScript)) {
    return "pgx-cli ir inspect";
  }
  return undefined;
}

function containsGhBacktickBody(script: string): boolean {
  return /(?:^|[;&|\n])\s*gh\s+pr\s+comment\b[^;&|\n]*--body(?:=|\s+)[^;&|\n]*`/.test(script);
}

function splitShellWords(script: string): string[] {
  return script.trim().split(/\s+/).filter(Boolean);
}

function replacementForPath(path: string | undefined): string | undefined {
  if (!path) return undefined;
  if (path === "/tmp/pgx_errors.log") return "pgx-cli logs errors";
  if (path === "/tmp/pgx_ir" || path.startsWith("/tmp/pgx_ir/")) return "pgx-cli ir inspect";
  return undefined;
}

function isLargeLogOrIrPath(path: string): boolean {
  return path === "/tmp/pgx_errors.log" || path === "/tmp/pgx_ir" || path.startsWith("/tmp/pgx_ir/");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function filesIn(dir: string, prefix: string, include: (name: string) => boolean): string[] {
  if (!existsSync(dir)) return [];
  const discovered: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const childPrefix = `${prefix}/${entry.name}`;
    const childPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      discovered.push(...filesIn(childPath, childPrefix, include));
    } else if (entry.isFile() && include(entry.name)) {
      discovered.push(childPrefix);
    }
  }
  return discovered;
}

function prefixRule(pattern: string[], replacement: string): string {
  const rendered = pattern.map((part) => JSON.stringify(part)).join(", ");
  return [
    "prefix_rule(",
    `    pattern = [${rendered}],`,
    '    decision = "forbidden",',
    `    justification = ${JSON.stringify(`Use ${replacement} so Mutagen, transcripts, and output limits are enforced.`)},`,
    ")",
  ].join("\n");
}
