import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

export type CommandPolicyDecision =
  | { decision: "allow"; reason: string }
  | { decision: "forbidden"; reason: string; replacement: string };

const blockedCommands = [
  ["ssh", "pgx-cli run thor -- ..."],
  ["docker", "pgx-cli run docker -- ..."],
  ["psql", "pgx-cli run psql ..."],
  ["pg_regress", "pgx-cli dev test ..."],
  ["ctest", "pgx-cli dev test ..."],
  ["cmake", "pgx-cli dev build ..."],
  ["ninja", "pgx-cli dev build ..."],
  ["tsp", "pgx-cli queue ..."],
  ["mutagen", "pgx-cli sync ..."],
  ["just", "pgx-cli ..."]
] as const;

const localInspectionCommands = new Set(["rg", "sed", "find", "ls", "pwd", "nl", "wc"]);

export function classifyAgentCommand(
  argv: string[],
  options: { root?: string; workflowScripts?: string[] } = {}
): CommandPolicyDecision {
  const command = argv[0] ?? "";
  const workflowScripts = options.workflowScripts ?? (options.root ? discoverWorkflowScripts(options.root) : []);
  const normalizedScripts = new Set(workflowScripts.flatMap((script) => [script, `./${script}`]));
  if (normalizedScripts.has(command)) {
    return forbid(command, "pgx-cli <typed workflow command>");
  }

  const blocked = blockedCommands.find(([binary]) => binary === command);
  if (blocked) {
    return forbid(command, blocked[1]);
  }
  if (command === "pgx-cli") {
    return { decision: "allow", reason: "pgx-cli gateway command" };
  }
  if (localInspectionCommands.has(command)) {
    return { decision: "allow", reason: "local read-only inspection command" };
  }
  if (command === "git" && ["status", "diff", "show"].includes(argv[1] ?? "")) {
    return { decision: "allow", reason: "local git inspection command" };
  }
  return { decision: "allow", reason: "not covered by pgx-lower agent workflow policy" };
}

export function discoverWorkflowScripts(root: string): string[] {
  return [
    ...filesIn(join(root, "scripts"), "scripts", (name) => name.endsWith(".sh")),
    ...filesIn(join(root, "tools", "scripts"), "tools/scripts", (name) => name.endsWith(".sh") || name.endsWith(".py")),
    ...filesIn(join(root, "benchmark"), "benchmark", (name) => name.endsWith(".py"))
  ].sort();
}

export function renderDefaultRules(options: { root?: string; workflowScripts?: string[] } = {}): string {
  const scripts = options.workflowScripts ?? (options.root ? discoverWorkflowScripts(options.root) : []);
  const chunks: string[] = [[
    "# Generated by `pgx-cli codex-policy rules`.",
    "# match: ssh comfy true",
    "# match: docker ps",
    "# match: psql -c 'SELECT 1'"
  ].join("\n")];
  for (const [command, replacement] of blockedCommands) {
    chunks.push(prefixRule([command], replacement));
  }
  for (const script of scripts) {
    chunks.push(prefixRule([script], "pgx-cli <typed workflow command>"));
    chunks.push(prefixRule([`./${script}`], "pgx-cli <typed workflow command>"));
  }
  return `${chunks.join("\n\n")}\n`;
}

export function runCodexPolicyCommand(args: string[], output: { stdout: string; stderr: string }): number {
  const [command, ...rest] = args;
  if (command === "rules") {
    output.stdout += renderDefaultRules({ root: process.cwd() });
    return 0;
  }
  if (command === "check") {
    const separator = rest.indexOf("--");
    const argv = separator === -1 ? rest : rest.slice(separator + 1);
    const decision = classifyAgentCommand(argv, { root: process.cwd() });
    output.stdout += `${JSON.stringify(decision, null, 2)}\n`;
    return decision.decision === "forbidden" ? 1 : 0;
  }
  output.stderr += "Usage: codex-policy <check -- <cmd...>|rules>\n";
  return 1;
}

function forbid(command: string, replacement: string): CommandPolicyDecision {
  return {
    decision: "forbidden",
    reason: `Use ${replacement} so Mutagen, transcripts, and output limits are enforced instead of raw ${command}.`,
    replacement
  };
}

function filesIn(dir: string, prefix: string, include: (name: string) => boolean): string[] {
  if (!existsSync(dir)) return [];
  const discovered: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const childPrefix = `${prefix}/${entry.name}`;
    const childPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      discovered.push(...filesIn(childPath, childPrefix, include));
    } else if (entry.isFile() && include(entry.name)) {
      discovered.push(childPrefix);
    }
  }
  return discovered;
}

function prefixRule(pattern: string[], replacement: string): string {
  const rendered = pattern.map((part) => JSON.stringify(part)).join(", ");
  return [
    "prefix_rule(",
    `    pattern = [${rendered}],`,
    '    decision = "forbidden",',
    `    justification = ${JSON.stringify(`Use ${replacement} so Mutagen, transcripts, and output limits are enforced.`)},`,
    ")",
  ].join("\n");
}
