import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, join, relative } from "node:path";

const pgFnRe = /PGX_TEST_FN\(\s*(\w+)\s*\)/g;

export function collectPgTestFunctions(text: string): string[] {
  return [...text.matchAll(pgFnRe)].map((match) => match[1] ?? "").filter((name) => name.length > 0);
}

export function generateUnitSql(sourceBasename: string, names: string[]): string {
  const lines = [
    `-- AUTOGENERATED by pgx-cli - do not edit by hand.\n-- Source: src/pgx-lower/test/${sourceBasename}\n\n`,
    "\\set ON_ERROR_STOP on\n",
    "\nCREATE SCHEMA IF NOT EXISTS test;\n"
  ];
  for (const name of names) {
    lines.push(
      `\nCREATE OR REPLACE FUNCTION test.${name}() RETURNS VOID\n` +
        `    AS '$libdir/pgx_lower', 'ts_test_${name}' LANGUAGE C VOLATILE;`
    );
  }
  lines.push("\n\nDO $$ BEGIN");
  for (const name of names) {
    lines.push(`\n    PERFORM test.${name}();`);
  }
  lines.push("\nEND $$;\n");
  lines.push("\nDROP SCHEMA test CASCADE;\n");
  return lines.join("");
}

export function writeUnitSqlFiles(root: string): string[] {
  const srcDir = join(root, "src/pgx-lower/test");
  const outDir = join(root, "tests/unit-tests/sql");
  mkdirSync(outDir, { recursive: true });
  const written: string[] = [];
  for (const file of readdirSync(srcDir).filter((entry) => entry.endsWith("_tests.cpp")).sort()) {
    const names = collectPgTestFunctions(readFileSync(join(srcDir, file), "utf8"));
    if (names.length === 0) continue;
    const group = basename(file, "_tests.cpp");
    const out = join(outDir, `${group}.sql`);
    rmSync(out, { force: true });
    writeFileSync(out, generateUnitSql(file, names));
    written.push(`${relative(root, out)} (${names.length} tests)`);
  }
  return written;
}
