import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, join, relative } from "node:path";

const pgFnRe = /PGX_TEST_FN\(\s*(\w+)\s*\)/g;

type Io = {
  stdout: string;
  stderr: string;
};

export function collectPgTestFunctions(text: string): string[] {
  return [...text.matchAll(pgFnRe)].map((match) => match[1] ?? "").filter((name) => name.length > 0);
}

export function generateUnitSql(sourceBasename: string, names: string[]): string {
  const lines = [
    `-- AUTOGENERATED by pgx-cli - do not edit by hand.\n-- Source: src/pgx-lower/test/${sourceBasename}\n\n`,
    "\\set ON_ERROR_STOP on\n",
    "\nCREATE SCHEMA IF NOT EXISTS test;\n"
  ];
  for (const name of names) {
    lines.push(
      `\nCREATE OR REPLACE FUNCTION test.${name}() RETURNS VOID\n` +
        `    AS '$libdir/pgx_lower', 'ts_test_${name}' LANGUAGE C VOLATILE;`
    );
  }
  lines.push("\n\nDO $$ BEGIN");
  for (const name of names) {
    lines.push(`\n    PERFORM test.${name}();`);
  }
  lines.push("\nEND $$;\n");
  lines.push("\nDROP SCHEMA test CASCADE;\n");
  return lines.join("");
}

export function writeUnitSqlFiles(root: string): string[] {
  const srcDir = join(root, "src/pgx-lower/test");
  const outDir = join(root, "tests/unit-tests/sql");
  mkdirSync(outDir, { recursive: true });
  const written: string[] = [];
  const sources = readdirSync(srcDir)
    .filter((entry) => entry.endsWith("_tests.cpp"))
    .sort()
    .map((file) => ({ file, names: collectPgTestFunctions(readFileSync(join(srcDir, file), "utf8")) }))
    .filter((source) => source.names.length > 0);
  const currentOutputs = new Set(sources.map((source) => `${basename(source.file, "_tests.cpp")}.sql`));
  for (const file of readdirSync(outDir).filter((entry) => entry.endsWith(".sql"))) {
    if (currentOutputs.has(file)) continue;
    const out = join(outDir, file);
    if (readFileSync(out, "utf8").startsWith("-- AUTOGENERATED by pgx-cli")) {
      rmSync(out, { force: true });
    }
  }
  for (const { file, names } of sources) {
    const group = basename(file, "_tests.cpp");
    const out = join(outDir, `${group}.sql`);
    rmSync(out, { force: true });
    writeFileSync(out, generateUnitSql(file, names));
    written.push(`${relative(root, out)} (${names.length} tests)`);
  }
  return written;
}

export function runUnitSqlCommand(args: readonly string[], io: Io): number {
  if (args.includes("--help") || args.includes("-h")) {
    io.stdout += unitSqlHelpText();
    return 0;
  }

  let root = process.cwd();
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--root") {
      const value = args[index + 1];
      if (!value) {
        io.stderr += unitSqlHelpText();
        return 1;
      }
      root = value;
      index += 1;
      continue;
    }
    io.stderr += unitSqlHelpText();
    return 1;
  }

  try {
    for (const line of writeUnitSqlFiles(root)) {
      io.stdout += `${line}\n`;
    }
    return 0;
  } catch (error) {
    io.stderr += `${error instanceof Error ? error.message : String(error)}\n`;
    return 1;
  }
}

function unitSqlHelpText(): string {
  return ["Usage: pgx-cli test unit-sql [--root <repo>]", "", "Generate pg_regress SQL wrappers for PGX_TEST_FN unit tests.", ""].join("\n");
}
