#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct DataSource {
 inline static mlir::util::FunctionSpec get =  mlir::util::FunctionSpec("runtime::DataSource::get", "_ZN7runtime10DataSource3getENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
};
struct DataSourceIteration {
 inline static mlir::util::FunctionSpec start =  mlir::util::FunctionSpec("runtime::DataSourceIteration::start", "_ZN7runtime19DataSourceIteration5startEPNS_16ExecutionContextENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec isValid =  mlir::util::FunctionSpec("runtime::DataSourceIteration::isValid", "_ZN7runtime19DataSourceIteration7isValidEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},false);
 inline static mlir::util::FunctionSpec next =  mlir::util::FunctionSpec("runtime::DataSourceIteration::next", "_ZN7runtime19DataSourceIteration4nextEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec access =  mlir::util::FunctionSpec("runtime::DataSourceIteration::access", "_ZN7runtime19DataSourceIteration6accessEPNS0_15RecordBatchInfoE",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec end =  mlir::util::FunctionSpec("runtime::DataSourceIteration::end", "_ZN7runtime19DataSourceIteration3endEPS0_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
};
}
