#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct DateRuntime {
 inline static mlir::util::FunctionSpec extractDay =  mlir::util::FunctionSpec("runtime::DateRuntime::extractDay", "_ZN7runtime11DateRuntime10extractDayEl",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},false);
 inline static mlir::util::FunctionSpec extractMonth =  mlir::util::FunctionSpec("runtime::DateRuntime::extractMonth", "_ZN7runtime11DateRuntime12extractMonthEl",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},false);
 inline static mlir::util::FunctionSpec extractYear =  mlir::util::FunctionSpec("runtime::DateRuntime::extractYear", "_ZN7runtime11DateRuntime11extractYearEl",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},false);
 inline static mlir::util::FunctionSpec subtractMonths =  mlir::util::FunctionSpec("runtime::DateRuntime::subtractMonths", "_ZN7runtime11DateRuntime14subtractMonthsEll",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},false);
 inline static mlir::util::FunctionSpec addMonths =  mlir::util::FunctionSpec("runtime::DateRuntime::addMonths", "_ZN7runtime11DateRuntime9addMonthsEll",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},false);
 inline static mlir::util::FunctionSpec ExtractFromDate =  mlir::util::FunctionSpec("runtime::DateRuntime::ExtractFromDate", "_ZN7runtime11DateRuntime15ExtractFromDateENS_8VarLen32El",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},false);
};
}
