#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct DumpRuntime {
 inline static mlir::util::FunctionSpec dumpIndex =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpIndex", "_ZN7runtime11DumpRuntime9dumpIndexEm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpInt =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpInt", "_ZN7runtime11DumpRuntime7dumpIntEbl",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpUInt =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpUInt", "_ZN7runtime11DumpRuntime8dumpUIntEbm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpBool =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpBool", "_ZN7runtime11DumpRuntime8dumpBoolEbb",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,1)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpDecimal =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpDecimal", "_ZN7runtime11DumpRuntime11dumpDecimalEbmmi",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,32)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpDate =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpDate", "_ZN7runtime11DumpRuntime8dumpDateEbl",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpTimestampSecond =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpTimestampSecond", "_ZN7runtime11DumpRuntime19dumpTimestampSecondEbm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpTimestampMilliSecond =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpTimestampMilliSecond", "_ZN7runtime11DumpRuntime24dumpTimestampMilliSecondEbm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpTimestampMicroSecond =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpTimestampMicroSecond", "_ZN7runtime11DumpRuntime24dumpTimestampMicroSecondEbm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpTimestampNanoSecond =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpTimestampNanoSecond", "_ZN7runtime11DumpRuntime23dumpTimestampNanoSecondEbm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpIntervalMonths =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpIntervalMonths", "_ZN7runtime11DumpRuntime18dumpIntervalMonthsEbj",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,32)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpIntervalDaytime =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpIntervalDaytime", "_ZN7runtime11DumpRuntime19dumpIntervalDaytimeEbm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpFloat =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpFloat", "_ZN7runtime11DumpRuntime9dumpFloatEbd",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::Float64Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpString =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpString", "_ZN7runtime11DumpRuntime10dumpStringEbNS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpChar =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpChar", "_ZN7runtime11DumpRuntime8dumpCharEbmm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
};
}
