#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct HashtableMetadata {
};
struct Hashtable {
 inline static mlir::util::FunctionSpec resize =  mlir::util::FunctionSpec("runtime::Hashtable::resize", "_ZN7runtime9Hashtable6resizeEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec appendEntryWithDeepCopy =  mlir::util::FunctionSpec("runtime::Hashtable::appendEntryWithDeepCopy", "_ZN7runtime9Hashtable23appendEntryWithDeepCopyEmmPvS1_mm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64),mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec create =  mlir::util::FunctionSpec("runtime::Hashtable::create", "_ZN7runtime9Hashtable6createEmmm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec destroy =  mlir::util::FunctionSpec("runtime::Hashtable::destroy", "_ZN7runtime9Hashtable7destroyEPS0_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec hex_dump_all =  mlir::util::FunctionSpec("runtime::Hashtable::hex_dump_all", "_ZNK7runtime9Hashtable12hex_dump_allEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
};
}
