#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct LazyJoinHashtable {
 inline static mlir::util::FunctionSpec create =  mlir::util::FunctionSpec("runtime::LazyJoinHashtable::create", "_ZN7runtime17LazyJoinHashtable6createEmm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec appendEntryWithDeepCopy =  mlir::util::FunctionSpec("runtime::LazyJoinHashtable::appendEntryWithDeepCopy", "_ZN7runtime17LazyJoinHashtable23appendEntryWithDeepCopyEmmPKhS2_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64),mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec finalize =  mlir::util::FunctionSpec("runtime::LazyJoinHashtable::finalize", "_ZN7runtime17LazyJoinHashtable8finalizeEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec resize =  mlir::util::FunctionSpec("runtime::LazyJoinHashtable::resize", "_ZN7runtime17LazyJoinHashtable6resizeEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec destroy =  mlir::util::FunctionSpec("runtime::LazyJoinHashtable::destroy", "_ZN7runtime17LazyJoinHashtable7destroyEPS0_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
};
}
