#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct PgSortState {
 inline static mlir::util::FunctionSpec appendTuple =  mlir::util::FunctionSpec("runtime::PgSortState::appendTuple", "_ZN7runtime11PgSortState11appendTupleEPKh",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec flushTuples =  mlir::util::FunctionSpec("runtime::PgSortState::flushTuples", "_ZNK7runtime11PgSortState11flushTuplesEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec performSort =  mlir::util::FunctionSpec("runtime::PgSortState::performSort", "_ZN7runtime11PgSortState11performSortEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec getNextTuple =  mlir::util::FunctionSpec("runtime::PgSortState::getNextTuple", "_ZN7runtime11PgSortState12getNextTupleEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec create =  mlir::util::FunctionSpec("runtime::PgSortState::create", "_ZN7runtime11PgSortState6createEmm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec destroy =  mlir::util::FunctionSpec("runtime::PgSortState::destroy", "_ZN7runtime11PgSortState7destroyEPS0_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
};
}
