#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct StringRuntime {
 inline static mlir::util::FunctionSpec compareEq =  mlir::util::FunctionSpec("runtime::StringRuntime::compareEq", "_ZN7runtime13StringRuntime9compareEqENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
 inline static mlir::util::FunctionSpec compareNEq =  mlir::util::FunctionSpec("runtime::StringRuntime::compareNEq", "_ZN7runtime13StringRuntime10compareNEqENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
 inline static mlir::util::FunctionSpec compareLt =  mlir::util::FunctionSpec("runtime::StringRuntime::compareLt", "_ZN7runtime13StringRuntime9compareLtENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
 inline static mlir::util::FunctionSpec compareGt =  mlir::util::FunctionSpec("runtime::StringRuntime::compareGt", "_ZN7runtime13StringRuntime9compareGtENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
 inline static mlir::util::FunctionSpec compareLte =  mlir::util::FunctionSpec("runtime::StringRuntime::compareLte", "_ZN7runtime13StringRuntime10compareLteENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
 inline static mlir::util::FunctionSpec compareGte =  mlir::util::FunctionSpec("runtime::StringRuntime::compareGte", "_ZN7runtime13StringRuntime10compareGteENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
 inline static mlir::util::FunctionSpec like =  mlir::util::FunctionSpec("runtime::StringRuntime::like", "_ZN7runtime13StringRuntime4likeENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
 inline static mlir::util::FunctionSpec startsWith =  mlir::util::FunctionSpec("runtime::StringRuntime::startsWith", "_ZN7runtime13StringRuntime10startsWithENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
 inline static mlir::util::FunctionSpec endsWith =  mlir::util::FunctionSpec("runtime::StringRuntime::endsWith", "_ZN7runtime13StringRuntime8endsWithENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
 inline static mlir::util::FunctionSpec toInt =  mlir::util::FunctionSpec("runtime::StringRuntime::toInt", "_ZN7runtime13StringRuntime5toIntENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},true);
 inline static mlir::util::FunctionSpec toFloat32 =  mlir::util::FunctionSpec("runtime::StringRuntime::toFloat32", "_ZN7runtime13StringRuntime9toFloat32ENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Float32Type::get(context)};},true);
 inline static mlir::util::FunctionSpec toFloat64 =  mlir::util::FunctionSpec("runtime::StringRuntime::toFloat64", "_ZN7runtime13StringRuntime9toFloat64ENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Float64Type::get(context)};},true);
 inline static mlir::util::FunctionSpec toDecimal =  mlir::util::FunctionSpec("runtime::StringRuntime::toDecimal", "_ZN7runtime13StringRuntime9toDecimalENS_8VarLen32Ei",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::IntegerType::get(context,32)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,128)};},true);
 inline static mlir::util::FunctionSpec fromInt =  mlir::util::FunctionSpec("runtime::StringRuntime::fromInt", "_ZN7runtime13StringRuntime7fromIntEl",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec fromFloat32 =  mlir::util::FunctionSpec("runtime::StringRuntime::fromFloat32", "_ZN7runtime13StringRuntime11fromFloat32Ef",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Float32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec fromFloat64 =  mlir::util::FunctionSpec("runtime::StringRuntime::fromFloat64", "_ZN7runtime13StringRuntime11fromFloat64Ed",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Float64Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec fromChar =  mlir::util::FunctionSpec("runtime::StringRuntime::fromChar", "_ZN7runtime13StringRuntime8fromCharEmm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec fromDecimal =  mlir::util::FunctionSpec("runtime::StringRuntime::fromDecimal", "_ZN7runtime13StringRuntime11fromDecimalEni",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,128),mlir::IntegerType::get(context,32)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec substr =  mlir::util::FunctionSpec("runtime::StringRuntime::substr", "_ZN7runtime13StringRuntime6substrENS_8VarLen32Emm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec findMatch =  mlir::util::FunctionSpec("runtime::StringRuntime::findMatch", "_ZN7runtime13StringRuntime9findMatchENS_8VarLen32ES1_mm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context),mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},true);
 inline static mlir::util::FunctionSpec concat =  mlir::util::FunctionSpec("runtime::StringRuntime::concat", "_ZN7runtime13StringRuntime6concatENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec concat3 =  mlir::util::FunctionSpec("runtime::StringRuntime::concat3", "_ZN7runtime13StringRuntime7concat3ENS_8VarLen32ES1_S1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec upper =  mlir::util::FunctionSpec("runtime::StringRuntime::upper", "_ZN7runtime13StringRuntime5upperENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec lower =  mlir::util::FunctionSpec("runtime::StringRuntime::lower", "_ZN7runtime13StringRuntime5lowerENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec substring =  mlir::util::FunctionSpec("runtime::StringRuntime::substring", "_ZN7runtime13StringRuntime9substringENS_8VarLen32Eii",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::IntegerType::get(context,32),mlir::IntegerType::get(context,32)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec length =  mlir::util::FunctionSpec("runtime::StringRuntime::length", "_ZN7runtime13StringRuntime6lengthENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,32)};},true);
 inline static mlir::util::FunctionSpec charLength =  mlir::util::FunctionSpec("runtime::StringRuntime::charLength", "_ZN7runtime13StringRuntime10charLengthENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,32)};},true);
 inline static mlir::util::FunctionSpec trim =  mlir::util::FunctionSpec("runtime::StringRuntime::trim", "_ZN7runtime13StringRuntime4trimENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec ltrim =  mlir::util::FunctionSpec("runtime::StringRuntime::ltrim", "_ZN7runtime13StringRuntime5ltrimENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec rtrim =  mlir::util::FunctionSpec("runtime::StringRuntime::rtrim", "_ZN7runtime13StringRuntime5rtrimENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};},false);
 inline static mlir::util::FunctionSpec ilike =  mlir::util::FunctionSpec("runtime::StringRuntime::ilike", "_ZN7runtime13StringRuntime5ilikeENS_8VarLen32ES1_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,1)};},true);
};
}
