#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct TableBuilder {
 inline static mlir::util::FunctionSpec create =  mlir::util::FunctionSpec("runtime::TableBuilder::create", "_ZN7runtime12TableBuilder6createENS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec destroy =  mlir::util::FunctionSpec("runtime::TableBuilder::destroy", "_ZN7runtime12TableBuilder7destroyEPS0_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec build =  mlir::util::FunctionSpec("runtime::TableBuilder::build", "_ZN7runtime12TableBuilder5buildEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec addBool =  mlir::util::FunctionSpec("runtime::TableBuilder::addBool", "_ZN7runtime12TableBuilder7addBoolEbb",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,1)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec addInt8 =  mlir::util::FunctionSpec("runtime::TableBuilder::addInt8", "_ZN7runtime12TableBuilder7addInt8Eba",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,8)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec addInt16 =  mlir::util::FunctionSpec("runtime::TableBuilder::addInt16", "_ZN7runtime12TableBuilder8addInt16Ebs",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,16)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec addInt32 =  mlir::util::FunctionSpec("runtime::TableBuilder::addInt32", "_ZN7runtime12TableBuilder8addInt32Ebi",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,32)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec addInt64 =  mlir::util::FunctionSpec("runtime::TableBuilder::addInt64", "_ZN7runtime12TableBuilder8addInt64Ebl",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec addFloat32 =  mlir::util::FunctionSpec("runtime::TableBuilder::addFloat32", "_ZN7runtime12TableBuilder10addFloat32Ebf",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::Float32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec addFloat64 =  mlir::util::FunctionSpec("runtime::TableBuilder::addFloat64", "_ZN7runtime12TableBuilder10addFloat64Ebd",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::Float64Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec addDecimal =  mlir::util::FunctionSpec("runtime::TableBuilder::addDecimal", "_ZN7runtime12TableBuilder10addDecimalEbn",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,128)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec addFixedSized =  mlir::util::FunctionSpec("runtime::TableBuilder::addFixedSized", "_ZN7runtime12TableBuilder13addFixedSizedEbl",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec addBinary =  mlir::util::FunctionSpec("runtime::TableBuilder::addBinary", "_ZN7runtime12TableBuilder9addBinaryEbNS_8VarLen32E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,1),mlir::util::VarLen32Type::get(context)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec setNextDecimalScale =  mlir::util::FunctionSpec("runtime::TableBuilder::setNextDecimalScale", "_ZN7runtime12TableBuilder19setNextDecimalScaleEi",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::IntegerType::get(context,32)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec nextRow =  mlir::util::FunctionSpec("runtime::TableBuilder::nextRow", "_ZN7runtime12TableBuilder7nextRowEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
};
}
