#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct Vector {
 inline static mlir::util::FunctionSpec resize =  mlir::util::FunctionSpec("runtime::Vector::resize", "_ZN7runtime6Vector6resizeEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec create =  mlir::util::FunctionSpec("runtime::Vector::create", "_ZN7runtime6Vector6createEmm",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64),mlir::IntegerType::get(context,64)};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec getLen =  mlir::util::FunctionSpec("runtime::Vector::getLen", "_ZNK7runtime6Vector6getLenEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},false);
 inline static mlir::util::FunctionSpec getCap =  mlir::util::FunctionSpec("runtime::Vector::getCap", "_ZNK7runtime6Vector6getCapEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},false);
 inline static mlir::util::FunctionSpec getPtr =  mlir::util::FunctionSpec("runtime::Vector::getPtr", "_ZNK7runtime6Vector6getPtrEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};},false);
 inline static mlir::util::FunctionSpec getTypeSize =  mlir::util::FunctionSpec("runtime::Vector::getTypeSize", "_ZNK7runtime6Vector11getTypeSizeEv",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::IntegerType::get(context,64)};},false);
 inline static mlir::util::FunctionSpec sort =  mlir::util::FunctionSpec("runtime::Vector::sort", "_ZN7runtime6Vector4sortEPFbPhS1_E",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::FunctionType::get(context, {mlir::util::RefType::get(context,mlir::IntegerType::get(context,8)),mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))}, {mlir::IntegerType::get(context,1)})};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec destroy =  mlir::util::FunctionSpec("runtime::Vector::destroy", "_ZN7runtime6Vector7destroyEPS0_",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::util::RefType::get(context,mlir::IntegerType::get(context,8))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
};
}
