#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct DateRuntime {
 inline static mlir::util::FunctionSpec extractDay =  mlir::util::FunctionSpec("runtime::DateRuntime::extractDay", "rt_dateruntime_extractday",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};},false);
 inline static mlir::util::FunctionSpec extractMonth =  mlir::util::FunctionSpec("runtime::DateRuntime::extractMonth", "rt_dateruntime_extractmonth",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};},false);
 inline static mlir::util::FunctionSpec extractYear =  mlir::util::FunctionSpec("runtime::DateRuntime::extractYear", "rt_dateruntime_extractyear",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};},false);
 inline static mlir::util::FunctionSpec subtractMonths =  mlir::util::FunctionSpec("runtime::DateRuntime::subtractMonths", "rt_dateruntime_subtractmonths",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};},false);
 inline static mlir::util::FunctionSpec addMonths =  mlir::util::FunctionSpec("runtime::DateRuntime::addMonths", "rt_dateruntime_addmonths",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};},false);
};
}
