#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct DumpRuntime {
 inline static mlir::util::FunctionSpec dumpIndex =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpIndex", "rt_dumpruntime_dumpindex",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpInt =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpInt", "rt_dumpruntime_dumpint",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpUInt =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpUInt", "rt_dumpruntime_dumpuint",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpBool =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpBool", "rt_dumpruntime_dumpbool",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,1))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpDecimal =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpDecimal", "rt_dumpruntime_dumpdecimal",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64)),mlir::Type(mlir::IntegerType::get(context,64)),mlir::Type(mlir::IntegerType::get(context,32))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpDate =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpDate", "rt_dumpruntime_dumpdate",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpTimestampSecond =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpTimestampSecond", "rt_dumpruntime_dumptimestampsecond",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpTimestampMilliSecond =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpTimestampMilliSecond", "rt_dumpruntime_dumptimestampmillisecond",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpTimestampMicroSecond =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpTimestampMicroSecond", "rt_dumpruntime_dumptimestampmicrosecond",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpTimestampNanoSecond =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpTimestampNanoSecond", "rt_dumpruntime_dumptimestampnanosecond",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpIntervalMonths =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpIntervalMonths", "rt_dumpruntime_dumpintervalmonths",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,32))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpIntervalDaytime =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpIntervalDaytime", "rt_dumpruntime_dumpintervaldaytime",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpFloat =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpFloat", "rt_dumpruntime_dumpfloat",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::Float64Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpString =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpString", "rt_dumpruntime_dumpstring",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
 inline static mlir::util::FunctionSpec dumpChar =  mlir::util::FunctionSpec("runtime::DumpRuntime::dumpChar", "rt_dumpruntime_dumpchar",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1)),mlir::Type(mlir::IntegerType::get(context,64)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{};},false);
};
}
