#include <lingodb/mlir/Dialect/util/FunctionHelper.h>
namespace rt {
struct StringRuntime {
 inline static mlir::util::FunctionSpec compareEq =  mlir::util::FunctionSpec("runtime::StringRuntime::compareEq", "rt_stringruntime_compareeq",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1))};},true);
 inline static mlir::util::FunctionSpec compareNEq =  mlir::util::FunctionSpec("runtime::StringRuntime::compareNEq", "rt_stringruntime_compareneq",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1))};},true);
 inline static mlir::util::FunctionSpec compareLt =  mlir::util::FunctionSpec("runtime::StringRuntime::compareLt", "rt_stringruntime_comparelt",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1))};},true);
 inline static mlir::util::FunctionSpec compareGt =  mlir::util::FunctionSpec("runtime::StringRuntime::compareGt", "rt_stringruntime_comparegt",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1))};},true);
 inline static mlir::util::FunctionSpec compareLte =  mlir::util::FunctionSpec("runtime::StringRuntime::compareLte", "rt_stringruntime_comparelte",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1))};},true);
 inline static mlir::util::FunctionSpec compareGte =  mlir::util::FunctionSpec("runtime::StringRuntime::compareGte", "rt_stringruntime_comparegte",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1))};},true);
 inline static mlir::util::FunctionSpec like =  mlir::util::FunctionSpec("runtime::StringRuntime::like", "rt_stringruntime_like",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1))};},true);
 inline static mlir::util::FunctionSpec startsWith =  mlir::util::FunctionSpec("runtime::StringRuntime::startsWith", "rt_stringruntime_startswith",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1))};},true);
 inline static mlir::util::FunctionSpec endsWith =  mlir::util::FunctionSpec("runtime::StringRuntime::endsWith", "rt_stringruntime_endswith",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,1))};},true);
 inline static mlir::util::FunctionSpec toInt =  mlir::util::FunctionSpec("runtime::StringRuntime::toInt", "rt_stringruntime_toint",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};},true);
 inline static mlir::util::FunctionSpec toFloat32 =  mlir::util::FunctionSpec("runtime::StringRuntime::toFloat32", "rt_stringruntime_tofloat32",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::Float32Type::get(context))};},true);
 inline static mlir::util::FunctionSpec toFloat64 =  mlir::util::FunctionSpec("runtime::StringRuntime::toFloat64", "rt_stringruntime_tofloat64",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::Float64Type::get(context))};},true);
 inline static mlir::util::FunctionSpec toDecimal =  mlir::util::FunctionSpec("runtime::StringRuntime::toDecimal", "rt_stringruntime_todecimal",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::IntegerType::get(context,32))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,128))};},true);
 inline static mlir::util::FunctionSpec fromInt =  mlir::util::FunctionSpec("runtime::StringRuntime::fromInt", "rt_stringruntime_fromint",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context))};},false);
 inline static mlir::util::FunctionSpec fromFloat32 =  mlir::util::FunctionSpec("runtime::StringRuntime::fromFloat32", "rt_stringruntime_fromfloat32",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::Float32Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context))};},false);
 inline static mlir::util::FunctionSpec fromFloat64 =  mlir::util::FunctionSpec("runtime::StringRuntime::fromFloat64", "rt_stringruntime_fromfloat64",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::Float64Type::get(context))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context))};},false);
 inline static mlir::util::FunctionSpec fromChar =  mlir::util::FunctionSpec("runtime::StringRuntime::fromChar", "rt_stringruntime_fromchar",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context))};},false);
 inline static mlir::util::FunctionSpec fromDecimal =  mlir::util::FunctionSpec("runtime::StringRuntime::fromDecimal", "rt_stringruntime_fromdecimal",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,128)),mlir::Type(mlir::IntegerType::get(context,32))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context))};},false);
 inline static mlir::util::FunctionSpec substr =  mlir::util::FunctionSpec("runtime::StringRuntime::substr", "rt_stringruntime_substr",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::IntegerType::get(context,64)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context))};},false);
 inline static mlir::util::FunctionSpec findMatch =  mlir::util::FunctionSpec("runtime::StringRuntime::findMatch", "rt_stringruntime_findmatch",  [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::util::VarLen32Type::get(context)),mlir::Type(mlir::IntegerType::get(context,64)),mlir::Type(mlir::IntegerType::get(context,64))};}, [](mlir::MLIRContext* context) { return std::vector<mlir::Type>{mlir::Type(mlir::IntegerType::get(context,64))};},true);
};
}
