-- AUTOGENERATED by scripts/gen_unit_test_sql.py — do not edit by hand.
-- Source: src/pgx-lower/test/ast_const_translation_tests.cpp

\set ON_ERROR_STOP on

CREATE SCHEMA IF NOT EXISTS test;

CREATE OR REPLACE FUNCTION test.ast_const_int32() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_ast_const_int32' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.ast_const_int64() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_ast_const_int64' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.ast_const_bool() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_ast_const_bool' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.ast_const_null() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_ast_const_null' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.ast_const_date() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_ast_const_date' LANGUAGE C VOLATILE;

DO $$ BEGIN
    PERFORM test.ast_const_int32();
    PERFORM test.ast_const_int64();
    PERFORM test.ast_const_bool();
    PERFORM test.ast_const_null();
    PERFORM test.ast_const_date();
END $$;

DROP SCHEMA test CASCADE;
