-- AUTOGENERATED by scripts/gen_unit_test_sql.py — do not edit by hand.
-- Source: src/pgx-lower/test/boolean_lowering_tests.cpp

\set ON_ERROR_STOP on

CREATE SCHEMA IF NOT EXISTS test;

CREATE OR REPLACE FUNCTION test.boolean_not_lowering() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_boolean_not_lowering' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.boolean_and_lowering() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_boolean_and_lowering' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.boolean_or_lowering() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_boolean_or_lowering' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.boolean_complex_expression() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_boolean_complex_expression' LANGUAGE C VOLATILE;

DO $$ BEGIN
    PERFORM test.boolean_not_lowering();
    PERFORM test.boolean_and_lowering();
    PERFORM test.boolean_or_lowering();
    PERFORM test.boolean_complex_expression();
END $$;

DROP SCHEMA test CASCADE;
