-- AUTOGENERATED by scripts/gen_unit_test_sql.py — do not edit by hand.
-- Source: src/pgx-lower/test/numeric_tests.cpp

\set ON_ERROR_STOP on

CREATE SCHEMA IF NOT EXISTS test;

CREATE OR REPLACE FUNCTION test.numeric_to_i128_zero() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_numeric_to_i128_zero' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.numeric_to_i128_positive() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_numeric_to_i128_positive' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.numeric_to_i128_negative() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_numeric_to_i128_negative' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.numeric_to_i128_rescale_up() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_numeric_to_i128_rescale_up' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.numeric_to_i128_scale_down() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_numeric_to_i128_scale_down' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.numeric_to_i128_large() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_numeric_to_i128_large' LANGUAGE C VOLATILE;

DO $$ BEGIN
    PERFORM test.numeric_to_i128_zero();
    PERFORM test.numeric_to_i128_positive();
    PERFORM test.numeric_to_i128_negative();
    PERFORM test.numeric_to_i128_rescale_up();
    PERFORM test.numeric_to_i128_scale_down();
    PERFORM test.numeric_to_i128_large();
END $$;

DROP SCHEMA test CASCADE;
