-- AUTOGENERATED by scripts/gen_unit_test_sql.py — do not edit by hand.
-- Source: src/pgx-lower/test/type_mapping_tests.cpp

\set ON_ERROR_STOP on

CREATE SCHEMA IF NOT EXISTS test;

CREATE OR REPLACE FUNCTION test.type_mapping_bool() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_bool' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.type_mapping_int16() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_int16' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.type_mapping_int32() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_int32' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.type_mapping_int64() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_int64' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.type_mapping_int128() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_int128' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.type_mapping_f32() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_f32' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.type_mapping_f64() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_f64' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.type_mapping_varlen() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_varlen' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.type_mapping_nullable_unwrap() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_nullable_unwrap' LANGUAGE C VOLATILE;
CREATE OR REPLACE FUNCTION test.type_mapping_unsupported() RETURNS VOID
    AS '$libdir/pgx_lower', 'ts_test_type_mapping_unsupported' LANGUAGE C VOLATILE;

DO $$ BEGIN
    PERFORM test.type_mapping_bool();
    PERFORM test.type_mapping_int16();
    PERFORM test.type_mapping_int32();
    PERFORM test.type_mapping_int64();
    PERFORM test.type_mapping_int128();
    PERFORM test.type_mapping_f32();
    PERFORM test.type_mapping_f64();
    PERFORM test.type_mapping_varlen();
    PERFORM test.type_mapping_nullable_unwrap();
    PERFORM test.type_mapping_unsupported();
END $$;

DROP SCHEMA test CASCADE;
